name: Convert obsidian links

on: 
    push:
        branches:
            - v4
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.1
        with:
          input: content # input folder
          output: data   # output folder
          index: true    # whether to index content